"""add_deleted_at_to_chat_sessions

Revision ID: 3fa412ff2977
Revises: 4135ee8d8c05
Create Date: 2026-02-05 06:51:44.765683

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3fa412ff2977'
down_revision: Union[str, Sequence[str], None] = '4135ee8d8c05'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('api_keys', 'id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='Primary key (UUID)',
               existing_nullable=False)
    op.alter_column('api_keys', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='Soft delete flag',
               existing_nullable=False)
    op.alter_column('api_keys', 'deleted_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Deletion timestamp',
               existing_nullable=True)
    op.create_index(op.f('ix_api_keys_id'), 'api_keys', ['id'], unique=False)
    op.add_column('chat_messages', sa.Column('is_deleted', sa.Boolean(), nullable=False, comment='Soft delete flag'))
    op.add_column('chat_messages', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='Deletion timestamp'))
    op.alter_column('chat_messages', 'id',
               existing_type=sa.UUID(),
               comment='Primary key (UUID)',
               existing_nullable=False)
    op.alter_column('chat_messages', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Creation timestamp',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('chat_messages', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Last update timestamp',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_chat_messages_is_deleted'), 'chat_messages', ['is_deleted'], unique=False)
    op.add_column('chat_sessions', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='Deletion timestamp'))
    op.alter_column('chat_sessions', 'id',
               existing_type=sa.UUID(),
               comment='Primary key (UUID)',
               existing_nullable=False)
    op.alter_column('chat_sessions', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Creation timestamp',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('chat_sessions', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Last update timestamp',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_chat_sessions_user_updated'), table_name='chat_sessions')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_chat_sessions_user_updated'), 'chat_sessions', ['user_id', sa.literal_column('updated_at DESC')], unique=False)
    op.alter_column('chat_sessions', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Last update timestamp',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('chat_sessions', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Creation timestamp',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('chat_sessions', 'id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='Primary key (UUID)',
               existing_nullable=False)
    op.drop_column('chat_sessions', 'deleted_at')
    op.drop_index(op.f('ix_chat_messages_is_deleted'), table_name='chat_messages')
    op.alter_column('chat_messages', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Last update timestamp',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('chat_messages', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Creation timestamp',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('chat_messages', 'id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='Primary key (UUID)',
               existing_nullable=False)
    op.drop_column('chat_messages', 'deleted_at')
    op.drop_column('chat_messages', 'is_deleted')
    op.drop_index(op.f('ix_api_keys_id'), table_name='api_keys')
    op.alter_column('api_keys', 'deleted_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Deletion timestamp',
               existing_nullable=True)
    op.alter_column('api_keys', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               comment='Soft delete flag',
               existing_nullable=False)
    op.alter_column('api_keys', 'id',
               existing_type=sa.UUID(),
               comment='Primary key (UUID)',
               existing_nullable=False)
    # ### end Alembic commands ###
