"""create_auth_tables

Revision ID: bd6fcbea44b8
Revises:
Create Date: 2026-02-04 07:31:12.675487

"""

import uuid
from datetime import datetime
from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy import column, table

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "bd6fcbea44b8"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "permissions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("module", sa.String(length=50), nullable=False),
        sa.Column("action", sa.String(length=50), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_permissions_id"), "permissions", ["id"], unique=False)
    op.create_index(
        op.f("ix_permissions_module"), "permissions", ["module"], unique=False
    )
    op.create_index(op.f("ix_permissions_name"), "permissions", ["name"], unique=True)
    op.create_table(
        "roles",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=50), nullable=False),
        sa.Column("display_name", sa.String(length=100), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("is_system", sa.Boolean(), nullable=False),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_roles_id"), "roles", ["id"], unique=False)
    op.create_index(op.f("ix_roles_is_deleted"), "roles", ["is_deleted"], unique=False)
    op.create_index(op.f("ix_roles_name"), "roles", ["name"], unique=True)
    op.create_table(
        "users",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("username", sa.String(length=50), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("hashed_password", sa.String(length=255), nullable=False),
        sa.Column("avatar_url", sa.String(length=500), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("is_superuser", sa.Boolean(), nullable=False),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("last_login_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_index(op.f("ix_users_id"), "users", ["id"], unique=False)
    op.create_index(op.f("ix_users_is_deleted"), "users", ["is_deleted"], unique=False)
    op.create_index(op.f("ix_users_username"), "users", ["username"], unique=True)
    op.create_table(
        "role_permissions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("role_id", sa.UUID(), nullable=False),
        sa.Column("permission_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["permission_id"], ["permissions.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["role_id"], ["roles.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "role_id", "permission_id", name="uq_role_permissions_role_permission"
        ),
    )
    op.create_index(
        op.f("ix_role_permissions_permission_id"),
        "role_permissions",
        ["permission_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_role_permissions_role_id"),
        "role_permissions",
        ["role_id"],
        unique=False,
    )
    op.create_table(
        "user_roles",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("role_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["role_id"], ["roles.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "role_id", name="uq_user_roles_user_role"),
    )
    op.create_index(
        op.f("ix_user_roles_role_id"), "user_roles", ["role_id"], unique=False
    )
    op.create_index(
        op.f("ix_user_roles_user_id"), "user_roles", ["user_id"], unique=False
    )
    # ### end Alembic commands ###

    # Seed default roles and permissions
    _seed_default_roles()
    _seed_default_permissions()
    _seed_role_permissions()


def _seed_default_roles() -> None:
    """Insert default system roles."""
    roles_table = table(
        "roles",
        column("id", sa.UUID()),
        column("name", sa.String()),
        column("display_name", sa.String()),
        column("description", sa.Text()),
        column("is_system", sa.Boolean()),
        column("is_deleted", sa.Boolean()),
        column("created_at", sa.DateTime()),
        column("updated_at", sa.DateTime()),
    )

    now = datetime.utcnow()
    roles = [
        {
            "id": uuid.uuid4(),
            "name": "admin",
            "display_name": "超级管理员",
            "description": "拥有所有权限",
            "is_system": True,
            "is_deleted": False,
            "created_at": now,
            "updated_at": now,
        },
        {
            "id": uuid.uuid4(),
            "name": "manager",
            "display_name": "管理员",
            "description": "可管理用户和配置",
            "is_system": True,
            "is_deleted": False,
            "created_at": now,
            "updated_at": now,
        },
        {
            "id": uuid.uuid4(),
            "name": "developer",
            "display_name": "开发者",
            "description": "可管理资源和规则",
            "is_system": True,
            "is_deleted": False,
            "created_at": now,
            "updated_at": now,
        },
        {
            "id": uuid.uuid4(),
            "name": "user",
            "display_name": "普通用户",
            "description": "仅可使用 Agent",
            "is_system": True,
            "is_deleted": False,
            "created_at": now,
            "updated_at": now,
        },
    ]

    op.bulk_insert(roles_table, roles)


def _seed_default_permissions() -> None:
    """Insert default system permissions."""
    permissions_table = table(
        "permissions",
        column("id", sa.UUID()),
        column("module", sa.String()),
        column("action", sa.String()),
        column("name", sa.String()),
        column("description", sa.Text()),
        column("created_at", sa.DateTime()),
    )

    now = datetime.utcnow()

    # Define permission structure: (module, action, description)
    permission_definitions = [
        # User management
        ("users", "view", "查看用户"),
        ("users", "create", "创建用户"),
        ("users", "edit", "编辑用户"),
        ("users", "delete", "删除用户"),
        # Role management
        ("roles", "view", "查看角色"),
        ("roles", "create", "创建角色"),
        ("roles", "edit", "编辑角色"),
        ("roles", "delete", "删除角色"),
        # Model management
        ("models", "view", "查看模型配置"),
        ("models", "create", "创建模型配置"),
        ("models", "edit", "编辑模型配置"),
        ("models", "delete", "删除模型配置"),
        # MCP connections
        ("mcp", "view", "查看 MCP 连接"),
        ("mcp", "create", "创建 MCP 连接"),
        ("mcp", "edit", "编辑 MCP 连接"),
        ("mcp", "delete", "删除 MCP 连接"),
        # Knowledge base
        ("knowledge", "view", "查看知识库"),
        ("knowledge", "create", "创建知识库"),
        ("knowledge", "edit", "编辑知识库"),
        ("knowledge", "delete", "删除知识库"),
        # Skills
        ("skills", "view", "查看 SKILL"),
        ("skills", "create", "创建 SKILL"),
        ("skills", "edit", "编辑 SKILL"),
        ("skills", "delete", "删除 SKILL"),
        # Rules
        ("rules", "view", "查看规则"),
        ("rules", "create", "创建规则"),
        ("rules", "edit", "编辑规则"),
        ("rules", "delete", "删除规则"),
        # Agent/Chat
        ("chat", "create", "创建会话"),
        ("chat", "view", "查看会话"),
        ("chat", "edit", "编辑会话"),
        ("chat", "delete", "删除会话"),
    ]

    permissions = [
        {
            "id": uuid.uuid4(),
            "module": module,
            "action": action,
            "name": f"{module}:{action}",
            "description": description,
            "created_at": now,
        }
        for module, action, description in permission_definitions
    ]

    op.bulk_insert(permissions_table, permissions)


def _seed_role_permissions() -> None:
    """Assign permissions to roles."""
    # Get role and permission IDs
    conn = op.get_bind()

    # Fetch roles
    roles = conn.execute(sa.text("SELECT id, name FROM roles")).fetchall()
    role_map = {name: id for id, name in roles}

    # Fetch permissions
    permissions = conn.execute(sa.text("SELECT id, name FROM permissions")).fetchall()
    permission_map = {name: id for id, name in permissions}

    role_permissions_table = table(
        "role_permissions",
        column("id", sa.UUID()),
        column("role_id", sa.UUID()),
        column("permission_id", sa.UUID()),
        column("created_at", sa.DateTime()),
    )

    now = datetime.utcnow()
    role_permissions = []

    # Admin: all permissions
    for perm_id in permission_map.values():
        role_permissions.append(
            {
                "id": uuid.uuid4(),
                "role_id": role_map["admin"],
                "permission_id": perm_id,
                "created_at": now,
            }
        )

    # Manager: user, role, model, chat permissions
    manager_perms = [
        "users:view",
        "users:create",
        "users:edit",
        "roles:view",
        "models:view",
        "models:create",
        "models:edit",
        "chat:view",
        "chat:create",
        "chat:edit",
        "chat:delete",
    ]
    for perm_name in manager_perms:
        if perm_name in permission_map:
            role_permissions.append(
                {
                    "id": uuid.uuid4(),
                    "role_id": role_map["manager"],
                    "permission_id": permission_map[perm_name],
                    "created_at": now,
                }
            )

    # Developer: model, mcp, knowledge, skills, rules, chat permissions
    developer_perms = [
        "models:view",
        "models:create",
        "models:edit",
        "models:delete",
        "mcp:view",
        "mcp:create",
        "mcp:edit",
        "mcp:delete",
        "knowledge:view",
        "knowledge:create",
        "knowledge:edit",
        "knowledge:delete",
        "skills:view",
        "skills:create",
        "skills:edit",
        "skills:delete",
        "rules:view",
        "rules:create",
        "rules:edit",
        "rules:delete",
        "chat:view",
        "chat:create",
        "chat:edit",
        "chat:delete",
    ]
    for perm_name in developer_perms:
        if perm_name in permission_map:
            role_permissions.append(
                {
                    "id": uuid.uuid4(),
                    "role_id": role_map["developer"],
                    "permission_id": permission_map[perm_name],
                    "created_at": now,
                }
            )

    # User: only chat permissions
    user_perms = [
        "chat:view",
        "chat:create",
        "chat:edit",
        "chat:delete",
    ]
    for perm_name in user_perms:
        if perm_name in permission_map:
            role_permissions.append(
                {
                    "id": uuid.uuid4(),
                    "role_id": role_map["user"],
                    "permission_id": permission_map[perm_name],
                    "created_at": now,
                }
            )

    if role_permissions:
        op.bulk_insert(role_permissions_table, role_permissions)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_user_roles_user_id"), table_name="user_roles")
    op.drop_index(op.f("ix_user_roles_role_id"), table_name="user_roles")
    op.drop_table("user_roles")
    op.drop_index(op.f("ix_role_permissions_role_id"), table_name="role_permissions")
    op.drop_index(
        op.f("ix_role_permissions_permission_id"), table_name="role_permissions"
    )
    op.drop_table("role_permissions")
    op.drop_index(op.f("ix_users_username"), table_name="users")
    op.drop_index(op.f("ix_users_is_deleted"), table_name="users")
    op.drop_index(op.f("ix_users_id"), table_name="users")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_table("users")
    op.drop_index(op.f("ix_roles_name"), table_name="roles")
    op.drop_index(op.f("ix_roles_is_deleted"), table_name="roles")
    op.drop_index(op.f("ix_roles_id"), table_name="roles")
    op.drop_table("roles")
    op.drop_index(op.f("ix_permissions_name"), table_name="permissions")
    op.drop_index(op.f("ix_permissions_module"), table_name="permissions")
    op.drop_index(op.f("ix_permissions_id"), table_name="permissions")
    op.drop_table("permissions")
    # ### end Alembic commands ###
